CREATE OR REPLACE VIEW ANALYTICS.VW_PRODUCT_PERFORMANCE AS
WITH product_metrics AS (
    SELECT
        FL.PART_ID,
        DP.PART_NAME,
        DP.MANUFACTURER,
        DP.BRAND,
        DP.PART_CATEGORY,
        DP.PART_MATERIAL,
        DP.SIZE_CATEGORY,
        DP.RETAIL_PRICE,
        DP.PRICE_TIER,
        COUNT(DISTINCT FL.ORDER_ID)                             AS TOTAL_ORDERS,
        COUNT(DISTINCT FL.CUSTOMER_ID)                          AS UNIQUE_CUSTOMERS,
        SUM(FL.QUANTITY)                                        AS TOTAL_UNITS_SOLD,
        SUM(FL.NET_PRICE)                                       AS TOTAL_NET_REVENUE,
        SUM(FL.GROSS_PRICE)                                     AS TOTAL_GROSS_REVENUE,
        SUM(FL.DISCOUNT_AMOUNT)                                 AS TOTAL_DISCOUNTS,
        ROUND(AVG(FL.DISCOUNT_RATE) * 100, 2)                  AS AVG_DISCOUNT_PCT,
        COUNT(CASE WHEN FL.IS_RETURNED THEN 1 END)              AS TOTAL_RETURNS,
        ROUND(AVG(FL.DELIVERY_DAYS), 1)                         AS AVG_DELIVERY_DAYS
    FROM MARTS.FACT_LINEITEM FL
    JOIN MARTS.DIM_PRODUCTS DP ON FL.PART_ID = DP.PART_ID
    GROUP BY 1, 2, 3, 4, 5, 6, 7, 8, 9
)
SELECT
    *,
    ROUND(TOTAL_NET_REVENUE / NULLIF(TOTAL_UNITS_SOLD, 0), 2)  AS AVG_SELLING_PRICE,
    ROUND((AVG_SELLING_PRICE - RETAIL_PRICE) / RETAIL_PRICE * 100, 2) AS PRICE_REALIZATION_PCT,
    RANK() OVER (ORDER BY TOTAL_NET_REVENUE DESC)              AS OVERALL_REVENUE_RANK,
    RANK() OVER (PARTITION BY PART_CATEGORY ORDER BY TOTAL_NET_REVENUE DESC) AS CATEGORY_REVENUE_RANK,
    ROUND(TOTAL_NET_REVENUE / SUM(TOTAL_NET_REVENUE) OVER () * 100, 4) AS REVENUE_SHARE_PCT,
    -- Cumulative Pareto
    ROUND(SUM(TOTAL_NET_REVENUE) OVER (ORDER BY TOTAL_NET_REVENUE DESC) /
          SUM(TOTAL_NET_REVENUE) OVER () * 100, 2)             AS CUMULATIVE_REVENUE_PCT,
    -- ABC classification
    CASE
        WHEN (SUM(TOTAL_NET_REVENUE) OVER (ORDER BY TOTAL_NET_REVENUE DESC) /
              SUM(TOTAL_NET_REVENUE) OVER ()) <= 0.80 THEN 'A'
        WHEN (SUM(TOTAL_NET_REVENUE) OVER (ORDER BY TOTAL_NET_REVENUE DESC) /
              SUM(TOTAL_NET_REVENUE) OVER ()) <= 0.95 THEN 'B'
        ELSE 'C'
    END                                                        AS ABC_CLASS
FROM product_metrics;


-- ============================================================
-- VIEW 6: Shipping Mode Analysis
-- ============================================================
CREATE OR REPLACE VIEW ANALYTICS.VW_SHIP_MODE_ANALYSIS AS
SELECT
    SHIP_MODE,
    COUNT(*)                                AS TOTAL_LINE_ITEMS,
    ROUND(AVG(DELIVERY_DAYS), 1)            AS AVG_DELIVERY_DAYS,
    MIN(DELIVERY_DAYS)                      AS MIN_DELIVERY_DAYS,
    MAX(DELIVERY_DAYS)                      AS MAX_DELIVERY_DAYS,
    ROUND(STDDEV(DELIVERY_DAYS), 2)         AS DELIVERY_STD_DEV,
    SUM(NET_PRICE)                          AS TOTAL_REVENUE,
    COUNT(CASE WHEN IS_RETURNED THEN 1 END) AS TOTAL_RETURNS,
    COUNT(CASE WHEN IS_ON_TIME THEN 1 END)  AS ON_TIME_COUNT,
    ROUND(COUNT(CASE WHEN IS_ON_TIME THEN 1 END) / COUNT(*) * 100, 2) AS ON_TIME_PCT
FROM MARTS.FACT_LINEITEM
GROUP BY 1
ORDER BY TOTAL_REVENUE DESC;