USE ROLE RETAIL_ANALYST;
USE WAREHOUSE ANALYTICS_WH;
USE DATABASE RETAIL_DW;

-- 1. Query data as it looked a short time ago
SELECT COUNT(*), SUM(ORDER_TOTAL_AMOUNT) AS TOTAL_REV
FROM MARTS.FACT_ORDERS
AT(OFFSET => -60);   -- 60 seconds ago (not 1hr/24hr — table is too new for that)

-- 2. Compare current vs a short time ago
SELECT 'NOW' AS snapshot, COUNT(*) AS total_orders, SUM(ORDER_TOTAL_AMOUNT) AS total_revenue
FROM MARTS.FACT_ORDERS
UNION ALL
SELECT '60_SEC_AGO', COUNT(*), SUM(ORDER_TOTAL_AMOUNT)
FROM MARTS.FACT_ORDERS AT(OFFSET => -60);

-- 3. Switch role+warehouse for the backup step (needs CREATE TABLE on MARTS)
USE ROLE RETAIL_ENGINEER;
USE WAREHOUSE TRANSFORM_WH;

CREATE OR REPLACE TABLE MARTS.FACT_ORDERS_BACKUP_RECENT AS
SELECT * FROM MARTS.FACT_ORDERS AT(OFFSET => -60);

SELECT 'Original', COUNT(*) FROM MARTS.FACT_ORDERS
UNION ALL
SELECT 'Backup',   COUNT(*) FROM MARTS.FACT_ORDERS_BACKUP_RECENT;

-- ============================================================
-- OPTIONAL: real delete + recovery demo (run as separate steps)
-- ============================================================
-- Step A: DELETE FROM MARTS.FACT_ORDERS WHERE ORDER_YEAR = 1992 AND ORDER_MONTH = 1;
-- Step B: SELECT QUERY_ID, QUERY_TEXT, START_TIME
--         FROM TABLE(INFORMATION_SCHEMA.QUERY_HISTORY())
--         WHERE QUERY_TEXT ILIKE '%DELETE FROM MARTS.FACT_ORDERS%'
--         ORDER BY START_TIME DESC LIMIT 1;
-- Step C: INSERT INTO MARTS.FACT_ORDERS
--         SELECT * FROM MARTS.FACT_ORDERS BEFORE(STATEMENT => '<paste-query-id>')
--         WHERE ORDER_YEAR = 1992 AND ORDER_MONTH = 1;