USE ROLE RETAIL_ENGINEER;
USE DATABASE RETAIL_DW;

-- 1. Daily Sales Metrics (expensive to compute on-the-fly)
CREATE OR REPLACE MATERIALIZED VIEW ANALYTICS.MV_DAILY_SALES AS
SELECT
    FO.ORDER_DATE,
    FO.ORDER_YEAR,
    FO.ORDER_MONTH,
    FO.ORDER_QUARTER,
    COUNT(DISTINCT FO.ORDER_ID)                     AS DAILY_ORDERS,
    COUNT(DISTINCT FO.CUSTOMER_ID)                  AS DAILY_CUSTOMERS,
    SUM(FL.NET_PRICE)                               AS DAILY_REVENUE,
    SUM(FL.QUANTITY)                                AS DAILY_UNITS,
    SUM(FL.DISCOUNT_AMOUNT)                         AS DAILY_DISCOUNTS,
    COUNT(CASE WHEN FL.IS_RETURNED THEN 1 END)      AS DAILY_RETURNS,
    COUNT(CASE WHEN FL.IS_ON_TIME THEN 1 END)       AS DAILY_ON_TIME
FROM MARTS.FACT_ORDERS FO
JOIN MARTS.FACT_LINEITEM FL ON FO.ORDER_ID = FL.ORDER_ID
GROUP BY 1, 2, 3, 4;

-- 2. Supplier Monthly Performance (heavy aggregation)
CREATE OR REPLACE MATERIALIZED VIEW ANALYTICS.MV_SUPPLIER_MONTHLY AS
SELECT
    FL.SUPPLIER_ID,
    FO.ORDER_YEAR,
    FO.ORDER_MONTH,
    COUNT(DISTINCT FL.ORDER_ID)                     AS MONTHLY_ORDERS,
    SUM(FL.NET_PRICE)                               AS MONTHLY_REVENUE,
    SUM(FL.QUANTITY)                                AS MONTHLY_UNITS,
    ROUND(AVG(FL.DELIVERY_DAYS), 2)                 AS AVG_DELIVERY_DAYS,
    COUNT(CASE WHEN FL.IS_RETURNED THEN 1 END)      AS MONTHLY_RETURNS
FROM MARTS.FACT_LINEITEM FL
JOIN MARTS.FACT_ORDERS FO ON FL.ORDER_ID = FO.ORDER_ID
GROUP BY 1, 2, 3;

-- Snowflake auto-refreshes these as base tables change
SHOW MATERIALIZED VIEWS IN SCHEMA ANALYTICS;