USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_DW;

-- Masking policy: Phone numbers
CREATE OR REPLACE MASKING POLICY MARTS.MASK_PHONE
AS (val STRING) RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('RETAIL_ADMIN', 'RETAIL_ENGINEER') THEN val
    WHEN CURRENT_ROLE() = 'RETAIL_ANALYST'                     THEN CONCAT(SUBSTR(val, 1, 3), '-***-****')
    ELSE '***-***-****'
END;

-- Masking policy: Customer names
CREATE OR REPLACE MASKING POLICY MARTS.MASK_CUSTOMER_NAME
AS (val STRING) RETURNS STRING ->
CASE
    WHEN CURRENT_ROLE() IN ('RETAIL_ADMIN', 'RETAIL_ENGINEER') THEN val
    WHEN CURRENT_ROLE() = 'RETAIL_ANALYST'                     THEN CONCAT(UPPER(SUBSTR(val, 1, 1)), '. ', 'CUSTOMER')
    ELSE 'REDACTED'
END;

-- Apply masking policies to DIM_CUSTOMERS
ALTER TABLE MARTS.DIM_CUSTOMERS MODIFY COLUMN PHONE_NUMBER
    SET MASKING POLICY MARTS.MASK_PHONE;

ALTER TABLE MARTS.DIM_CUSTOMERS MODIFY COLUMN CUSTOMER_NAME
    SET MASKING POLICY MARTS.MASK_CUSTOMER_NAME;

-- Test as different roles
USE ROLE RETAIL_ADMIN;
SELECT CUSTOMER_ID, CUSTOMER_NAME, PHONE_NUMBER FROM MARTS.DIM_CUSTOMERS LIMIT 3;
-- Shows full data

USE ROLE RETAIL_VIEWER;
SELECT CUSTOMER_ID, CUSTOMER_NAME, PHONE_NUMBER FROM MARTS.DIM_CUSTOMERS LIMIT 3;
-- Shows masked data: "J. CUSTOMER" | "212-***-****"

-- Row Access Policy — region-based data segmentation
CREATE OR REPLACE ROW ACCESS POLICY MARTS.POLICY_REGION_ACCESS
AS (region_name VARCHAR) RETURNS BOOLEAN ->
CASE
    WHEN CURRENT_ROLE() IN ('RETAIL_ADMIN', 'RETAIL_ENGINEER', 'RETAIL_ANALYST') THEN TRUE
    ELSE region_name = 'AMERICA'  -- VIEWER only sees Americas
END;

ALTER TABLE MARTS.DIM_CUSTOMERS
    ADD ROW ACCESS POLICY MARTS.POLICY_REGION_ACCESS ON (REGION_NAME);

SHOW MASKING POLICIES IN SCHEMA MARTS;