-- NOTE: MASKING POLICY / ROW ACCESS POLICY require Enterprise Edition+.
-- Workaround: SECURE VIEWS using CURRENT_ROLE() — same protection,
-- standard SQL, works on any edition.

USE ROLE RETAIL_ENGINEER;
USE WAREHOUSE TRANSFORM_WH;
USE DATABASE RETAIL_DW;

CREATE OR REPLACE SECURE VIEW ANALYTICS.VW_CUSTOMERS_MASKED AS
SELECT
    CUSTOMER_ID,
    CASE
        WHEN CURRENT_ROLE() IN ('RETAIL_ADMIN', 'RETAIL_ENGINEER') THEN CUSTOMER_NAME
        WHEN CURRENT_ROLE() = 'RETAIL_ANALYST'                     THEN CONCAT(UPPER(SUBSTR(CUSTOMER_NAME,1,1)), '. CUSTOMER')
        ELSE 'REDACTED'
    END AS CUSTOMER_NAME,
    CASE
        WHEN CURRENT_ROLE() IN ('RETAIL_ADMIN', 'RETAIL_ENGINEER') THEN PHONE_NUMBER
        WHEN CURRENT_ROLE() = 'RETAIL_ANALYST'                     THEN CONCAT(SUBSTR(PHONE_NUMBER,1,3), '-***-****')
        ELSE '***-***-****'
    END AS PHONE_NUMBER,
    MARKET_SEGMENT, CUSTOMER_TIER, NATION_NAME, REGION_NAME, GEO_GROUP
FROM MARTS.DIM_CUSTOMERS;

CREATE OR REPLACE SECURE VIEW ANALYTICS.VW_CUSTOMERS_REGION_FILTERED AS
SELECT * FROM ANALYTICS.VW_CUSTOMERS_MASKED
WHERE CASE
    WHEN CURRENT_ROLE() IN ('RETAIL_ADMIN', 'RETAIL_ENGINEER', 'RETAIL_ANALYST') THEN TRUE
    ELSE REGION_NAME = 'AMERICA'
END;

-- Test as ADMIN — full data expected
USE ROLE RETAIL_ADMIN;
SELECT CUSTOMER_ID, CUSTOMER_NAME, PHONE_NUMBER FROM ANALYTICS.VW_CUSTOMERS_MASKED LIMIT 3;

-- Test as VIEWER — masked data expected
USE ROLE RETAIL_VIEWER;
USE WAREHOUSE ANALYTICS_WH;   -- RETAIL_VIEWER only has USAGE on ANALYTICS_WH
SELECT CUSTOMER_ID, CUSTOMER_NAME, PHONE_NUMBER FROM ANALYTICS.VW_CUSTOMERS_MASKED LIMIT 3;

SHOW VIEWS LIKE 'VW_CUSTOMERS%' IN SCHEMA ANALYTICS;