CREATE OR REPLACE TABLE MARTS.DIM_PRODUCTS AS
SELECT
    P.PART_ID,
    P.PART_NAME,
    P.MANUFACTURER,
    P.BRAND,
    P.PART_TYPE,
    P.PART_CATEGORY,
    P.PART_MATERIAL,
    P.SIZE_VALUE,
    P.SIZE_CATEGORY,
    P.CONTAINER_TYPE,
    P.RETAIL_PRICE,
    P.PRICE_TIER,
    P.STAGED_AT                             AS CREATED_AT
FROM STAGING.STG_PRODUCTS P;