USE ROLE RETAIL_ENGINEER;
USE DATABASE RETAIL_DW;

-- DQ Results table
CREATE OR REPLACE TABLE MONITORING.DQ_RESULTS (
    CHECK_ID        NUMBER AUTOINCREMENT,
    RUN_TIMESTAMP   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    LAYER           VARCHAR(20),     -- RAW | STAGING | MARTS
    TABLE_NAME      VARCHAR(100),
    CHECK_NAME      VARCHAR(100),
    STATUS          VARCHAR(10),     -- PASS | FAIL | WARN
    ROWS_CHECKED    NUMBER,
    ROWS_FAILED     NUMBER,
    FAILURE_RATE_PCT NUMBER(6,2),
    DETAILS         VARCHAR(500)
);

-- ============================================================
-- Run all DQ checks in one shot
-- ============================================================
INSERT INTO MONITORING.DQ_RESULTS
    (LAYER, TABLE_NAME, CHECK_NAME, STATUS, ROWS_CHECKED, ROWS_FAILED, FAILURE_RATE_PCT, DETAILS)

-- CHECK 1: No NULL primary keys in orders
SELECT
    'MARTS', 'FACT_ORDERS', 'NULL_PRIMARY_KEY',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    (SELECT COUNT(*) FROM MARTS.FACT_ORDERS),
    COUNT(*),
    ROUND(COUNT(*) / NULLIF((SELECT COUNT(*) FROM MARTS.FACT_ORDERS), 0) * 100, 4),
    'Orders where ORDER_ID is NULL'
FROM MARTS.FACT_ORDERS WHERE ORDER_ID IS NULL

UNION ALL

-- CHECK 2: No orphaned line items (line items without a parent order)
SELECT
    'MARTS', 'FACT_LINEITEM', 'ORPHANED_LINE_ITEMS',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    (SELECT COUNT(*) FROM MARTS.FACT_LINEITEM),
    COUNT(*),
    ROUND(COUNT(*) / NULLIF((SELECT COUNT(*) FROM MARTS.FACT_LINEITEM), 0) * 100, 4),
    'Line items without a matching order in FACT_ORDERS'
FROM MARTS.FACT_LINEITEM FL
WHERE NOT EXISTS (
    SELECT 1 FROM MARTS.FACT_ORDERS FO WHERE FO.ORDER_ID = FL.ORDER_ID
)

UNION ALL

-- CHECK 3: No negative revenue
SELECT
    'MARTS', 'FACT_LINEITEM', 'NEGATIVE_NET_PRICE',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    (SELECT COUNT(*) FROM MARTS.FACT_LINEITEM),
    COUNT(*),
    ROUND(COUNT(*) / NULLIF((SELECT COUNT(*) FROM MARTS.FACT_LINEITEM), 0) * 100, 4),
    'Line items with negative NET_PRICE'
FROM MARTS.FACT_LINEITEM WHERE NET_PRICE < 0

UNION ALL

-- CHECK 4: All orders have a matching customer
SELECT
    'MARTS', 'FACT_ORDERS', 'INVALID_CUSTOMER_FK',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    (SELECT COUNT(*) FROM MARTS.FACT_ORDERS),
    COUNT(*),
    ROUND(COUNT(*) / NULLIF((SELECT COUNT(*) FROM MARTS.FACT_ORDERS), 0) * 100, 4),
    'Orders with no matching customer in DIM_CUSTOMERS'
FROM MARTS.FACT_ORDERS FO
WHERE NOT EXISTS (
    SELECT 1 FROM MARTS.DIM_CUSTOMERS DC WHERE DC.CUSTOMER_ID = FO.CUSTOMER_ID
)

UNION ALL

-- CHECK 5: Date range sanity
SELECT
    'MARTS', 'FACT_ORDERS', 'ORDER_DATE_RANGE',
    CASE WHEN MIN(ORDER_DATE) >= '1990-01-01' AND MAX(ORDER_DATE) < CURRENT_DATE THEN 'PASS' ELSE 'FAIL' END,
    (SELECT COUNT(*) FROM MARTS.FACT_ORDERS),
    0,
    0,
    CONCAT('Range: ', MIN(ORDER_DATE)::VARCHAR, ' to ', MAX(ORDER_DATE)::VARCHAR)
FROM MARTS.FACT_ORDERS

UNION ALL

-- CHECK 6: Discount rate must be between 0 and 1
SELECT
    'MARTS', 'FACT_LINEITEM', 'DISCOUNT_RATE_RANGE',
    CASE WHEN COUNT(*) = 0 THEN 'PASS' ELSE 'FAIL' END,
    (SELECT COUNT(*) FROM MARTS.FACT_LINEITEM),
    COUNT(*),
    ROUND(COUNT(*) / NULLIF((SELECT COUNT(*) FROM MARTS.FACT_LINEITEM), 0) * 100, 4),
    'Line items where discount_rate is not between 0 and 1'
FROM MARTS.FACT_LINEITEM
WHERE DISCOUNT_RATE < 0 OR DISCOUNT_RATE > 1

UNION ALL

-- CHECK 7: Staging vs Raw row count (completeness)
SELECT
    'STAGING', 'STG_ORDERS', 'STAGING_COMPLETENESS',
    CASE WHEN ABS(1 - s.cnt / NULLIF(r.cnt, 0)) < 0.001 THEN 'PASS' ELSE 'WARN' END,
    r.cnt,
    ABS(r.cnt - s.cnt),
    ROUND(ABS(1 - s.cnt / NULLIF(r.cnt, 0)) * 100, 4),
    CONCAT('RAW: ', r.cnt, ' | STAGING: ', s.cnt, ' | Filtered: ', (r.cnt - s.cnt))
FROM
    (SELECT COUNT(*) AS cnt FROM RAW.ORDERS) r,
    (SELECT COUNT(*) AS cnt FROM STAGING.STG_ORDERS) s;

-- View latest DQ results
SELECT
    CHECK_NAME,
    TABLE_NAME,
    STATUS,
    ROWS_FAILED,
    FAILURE_RATE_PCT,
    DETAILS,
    RUN_TIMESTAMP
FROM MONITORING.DQ_RESULTS
ORDER BY RUN_TIMESTAMP DESC, STATUS DESC;

-- Summary dashboard
SELECT
    STATUS,
    COUNT(*) AS CHECKS_COUNT
FROM MONITORING.DQ_RESULTS
WHERE RUN_TIMESTAMP = (SELECT MAX(RUN_TIMESTAMP) FROM MONITORING.DQ_RESULTS)
GROUP BY 1;