USE ROLE RETAIL_ENGINEER;
USE WAREHOUSE TRANSFORM_WH;
USE DATABASE RETAIL_DW;
USE SCHEMA RAW;

-- ORDERS
CREATE OR REPLACE TABLE RAW.ORDERS AS
SELECT
    O_ORDERKEY,
    O_CUSTKEY,
    O_ORDERSTATUS,
    O_TOTALPRICE,
    O_ORDERDATE,
    O_ORDERPRIORITY,
    O_CLERK,
    O_SHIPPRIORITY,
    O_COMMENT,
    CURRENT_TIMESTAMP()  AS _LOADED_AT,
    'TPCH_SF1'           AS _SOURCE_SYSTEM,
    'ORDERS'             AS _SOURCE_TABLE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;

-- LINEITEM
CREATE OR REPLACE TABLE RAW.LINEITEM AS
SELECT
    L_ORDERKEY,
    L_PARTKEY,
    L_SUPPKEY,
    L_LINENUMBER,
    L_QUANTITY,
    L_EXTENDEDPRICE,
    L_DISCOUNT,
    L_TAX,
    L_RETURNFLAG,
    L_LINESTATUS,
    L_SHIPDATE,
    L_COMMITDATE,
    L_RECEIPTDATE,
    L_SHIPINSTRUCT,
    L_SHIPMODE,
    L_COMMENT,
    CURRENT_TIMESTAMP() AS _LOADED_AT,
    'TPCH_SF1'          AS _SOURCE_SYSTEM,
    'LINEITEM'          AS _SOURCE_TABLE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;

-- CUSTOMER
CREATE OR REPLACE TABLE RAW.CUSTOMER AS
SELECT
    C_CUSTKEY,
    C_NAME,
    C_ADDRESS,
    C_NATIONKEY,
    C_PHONE,
    C_ACCTBAL,
    C_MKTSEGMENT,
    C_COMMENT,
    CURRENT_TIMESTAMP() AS _LOADED_AT,
    'TPCH_SF1'          AS _SOURCE_SYSTEM,
    'CUSTOMER'          AS _SOURCE_TABLE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

-- SUPPLIER
CREATE OR REPLACE TABLE RAW.SUPPLIER AS
SELECT
    S_SUPPKEY,
    S_NAME,
    S_ADDRESS,
    S_NATIONKEY,
    S_PHONE,
    S_ACCTBAL,
    S_COMMENT,
    CURRENT_TIMESTAMP() AS _LOADED_AT,
    'TPCH_SF1'          AS _SOURCE_SYSTEM,
    'SUPPLIER'          AS _SOURCE_TABLE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER;

-- PART (Products)
CREATE OR REPLACE TABLE RAW.PART AS
SELECT
    P_PARTKEY,
    P_NAME,
    P_MFGR,
    P_BRAND,
    P_TYPE,
    P_SIZE,
    P_CONTAINER,
    P_RETAILPRICE,
    P_COMMENT,
    CURRENT_TIMESTAMP() AS _LOADED_AT,
    'TPCH_SF1'          AS _SOURCE_SYSTEM,
    'PART'              AS _SOURCE_TABLE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;

-- PARTSUPP
CREATE OR REPLACE TABLE RAW.PARTSUPP AS
SELECT
    PS_PARTKEY,
    PS_SUPPKEY,
    PS_AVAILQTY,
    PS_SUPPLYCOST,
    PS_COMMENT,
    CURRENT_TIMESTAMP() AS _LOADED_AT,
    'TPCH_SF1'          AS _SOURCE_SYSTEM,
    'PARTSUPP'          AS _SOURCE_TABLE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP;

-- NATION
CREATE OR REPLACE TABLE RAW.NATION AS
SELECT
    N_NATIONKEY,
    N_NAME,
    N_REGIONKEY,
    N_COMMENT,
    CURRENT_TIMESTAMP() AS _LOADED_AT,
    'TPCH_SF1'          AS _SOURCE_SYSTEM,
    'NATION'            AS _SOURCE_TABLE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;

-- REGION
CREATE OR REPLACE TABLE RAW.REGION AS
SELECT
    R_REGIONKEY,
    R_NAME,
    R_COMMENT,
    CURRENT_TIMESTAMP() AS _LOADED_AT,
    'TPCH_SF1'          AS _SOURCE_SYSTEM,
    'REGION'            AS _SOURCE_TABLE
FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;

-- Verify row counts
SELECT 'ORDERS'   AS tbl, COUNT(*) AS row_count FROM RAW.ORDERS    UNION ALL
SELECT 'LINEITEM',        COUNT(*)          FROM RAW.LINEITEM  UNION ALL
SELECT 'CUSTOMER',        COUNT(*)          FROM RAW.CUSTOMER  UNION ALL
SELECT 'SUPPLIER',        COUNT(*)          FROM RAW.SUPPLIER  UNION ALL
SELECT 'PART',            COUNT(*)          FROM RAW.PART      UNION ALL
SELECT 'PARTSUPP',        COUNT(*)          FROM RAW.PARTSUPP  UNION ALL
SELECT 'NATION',          COUNT(*)          FROM RAW.NATION    UNION ALL
SELECT 'REGION',          COUNT(*)          FROM RAW.REGION
ORDER BY tbl;