-- ============================================================
-- ROLE-BASED ACCESS CONTROL (RBAC)
-- ============================================================

USE ROLE ACCOUNTADMIN;

-- Create roles
CREATE ROLE IF NOT EXISTS RETAIL_ADMIN    COMMENT = 'Full admin access to RetailDW';
CREATE ROLE IF NOT EXISTS RETAIL_ENGINEER COMMENT = 'Build and transform data pipelines';
CREATE ROLE IF NOT EXISTS RETAIL_ANALYST  COMMENT = 'Read access to marts and analytics';
CREATE ROLE IF NOT EXISTS RETAIL_VIEWER   COMMENT = 'Read-only access to analytics views';

-- Role hierarchy (parent inherits child privileges)
GRANT ROLE RETAIL_ENGINEER TO ROLE RETAIL_ADMIN;
GRANT ROLE RETAIL_ANALYST  TO ROLE RETAIL_ADMIN;
GRANT ROLE RETAIL_VIEWER   TO ROLE RETAIL_ANALYST;

-- Warehouse grants
GRANT ALL ON WAREHOUSE ANALYTICS_WH  TO ROLE RETAIL_ADMIN;
GRANT ALL ON WAREHOUSE TRANSFORM_WH  TO ROLE RETAIL_ADMIN;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH TO ROLE RETAIL_ENGINEER;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE RETAIL_ANALYST;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH TO ROLE RETAIL_VIEWER;

-- Database grants
GRANT OWNERSHIP ON DATABASE RETAIL_DW TO ROLE RETAIL_ADMIN COPY CURRENT GRANTS;
GRANT ALL PRIVILEGES ON DATABASE RETAIL_DW TO ROLE RETAIL_ENGINEER;
GRANT USAGE ON DATABASE RETAIL_DW TO ROLE RETAIL_ANALYST;
GRANT USAGE ON DATABASE RETAIL_DW TO ROLE RETAIL_VIEWER;

-- Schema-level grants
GRANT ALL ON ALL SCHEMAS IN DATABASE RETAIL_DW TO ROLE RETAIL_ENGINEER;
GRANT USAGE ON SCHEMA RETAIL_DW.MARTS      TO ROLE RETAIL_ANALYST;
GRANT USAGE ON SCHEMA RETAIL_DW.ANALYTICS  TO ROLE RETAIL_ANALYST;
GRANT USAGE ON SCHEMA RETAIL_DW.ANALYTICS  TO ROLE RETAIL_VIEWER;

-- Table/view grants
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_DW.MARTS     TO ROLE RETAIL_ANALYST;
GRANT SELECT ON ALL VIEWS  IN SCHEMA RETAIL_DW.ANALYTICS  TO ROLE RETAIL_ANALYST;
GRANT SELECT ON ALL VIEWS  IN SCHEMA RETAIL_DW.ANALYTICS  TO ROLE RETAIL_VIEWER;

-- Future grants (auto-grant to new objects)
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_DW.MARTS     TO ROLE RETAIL_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA RETAIL_DW.ANALYTICS  TO ROLE RETAIL_ANALYST;
GRANT SELECT ON FUTURE VIEWS  IN SCHEMA RETAIL_DW.ANALYTICS  TO ROLE RETAIL_VIEWER;

-- Assign admin role to your user (replace YOUR_USERNAME)
GRANT ROLE RETAIL_ADMIN TO USER YOUR_USERNAME;

SHOW GRANTS TO ROLE RETAIL_ANALYST;