CREATE OR REPLACE TABLE MARTS.FACT_ORDERS AS
SELECT
    O.ORDER_ID,
    O.CUSTOMER_ID,
    DD.DATE_KEY                             AS ORDER_DATE_KEY,
    O.ORDER_DATE,
    O.ORDER_STATUS_CODE,
    O.ORDER_STATUS_DESC,
    O.ORDER_PRIORITY,
    O.ORDER_VALUE_TIER,
    O.ORDER_TOTAL_AMOUNT,
    O.SHIPPING_PRIORITY,
    O.CLERK,
    O.ORDER_YEAR,
    O.ORDER_MONTH,
    O.ORDER_QUARTER,
    O.ORDER_DAY_NAME,
    O.ORDER_DAY_OF_WEEK,
    -- Running order count per customer (window function)
    ROW_NUMBER() OVER (
        PARTITION BY O.CUSTOMER_ID
        ORDER BY O.ORDER_DATE, O.ORDER_ID
    )                                       AS CUSTOMER_ORDER_SEQ,
    O.STAGED_AT                             AS LOADED_AT
FROM STAGING.STG_ORDERS O
LEFT JOIN MARTS.DIM_DATE DD ON O.ORDER_DATE = DD.FULL_DATE;